### ISSUE TITLE
Proof of Concept: DNS Caching mitigation

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#292]
**What**

While we have integrated with the advanced scheduling for KCP to allow us to ensure a reasonable amount of time is given to allow DNS to update and propagate there will be cases where clients have not yet got the new DNS or applications that cannot tolerate allowing the workload to run on two different locations at once.

We should investigate what is possible with skupper and whether we can configure it to proxy any requests that hit the incorrect cluster to be sent to the new cluster. 

Ideal flow:
- don't allow the Ingress and service to be deleted
- allow the workload to move after TTL
- Reprogram the Ingress and Service to leverage Skupper

**Comment by david-martin** [comment]
*Update on progress*

I've pushed up some notes and a script to my fork at https://github.com/david-martin/kcp-glbc/tree/292-skupper-poc
The notes at https://github.com/david-martin/kcp-glbc/blob/292-skupper-poc/skupper_poc.md#sample-app-setup show:

1. setting up 2 clusters locally
2. running glbc locally with env vars for route53
3. deploying a sample app to 2 placements
4. configuring 2 skupper sites, with a link between the 2 downstream namespaces (done directly in the pclusters)
5. exposing the sample app service on cluster 2 to cluster 1 via the skupper network

The next logical step is to delete the placement for cluster 1 and transform the ingress on cluster 1 to route to the skupper service (so that traffic now gets proxied to the service on cluster 2 via skupper)
However, I've hit an issue where the soft finalizers on the resources in cluster 1 aren't being respected, and the entire namespace on cluster 1 is deleted straight away. 
I've had some conversations on slack https://kubernetes.slack.com/archives/C021U8WSAFK/p1667839086399439 and directly with Joaquim about this (waiting on an update on if it's a bug or something that hasn't been implemented yet)

I've paused this spike for now until there's a way past this problem.
Once that's resolved, the next step would be to modify the ingress controller to transform the rules just on cluster 1 to route to the skupper service, and ultimately prove the feasibility of this.

A few things that could be tidied up with this spike:
- move the exposing of the service into glbc code, and 'assume' that the other skupper pieces are handled by something else
- auto-detect if skupper is available in synctargets and only try to execute this migration logic then
- add a timeout for the exposed service before it's deleted (perhaps configurable by the user)
- see how feasible it is to actually install the skupper router and controllers from kcp into both downstream namespace (The main difference in resources between 2 clusters is in the linking, where 1 skupper instance generates a token, and the other is told what the token is. This sounds possible to do via kcp tranforms targetting eitiher cluster)

So, there's a lot more than can be done here, but it's blocked at present

**Comment by maleck13** [comment]
I wonder could we progress by not deleting the placement but instead trigger the transform to happen in some way to show this is what would happen?
Or if there is a relatively simple fix to the namespace deletion, we could add a fix and use a custom syncer image?

**Comment by david-martin** [comment]
> instead trigger the transform to happen in some way to show this is what would happen

Yes, thinking further on this we can proceed with some of the other steps, just not verify e2e the complete flow.



> a relatively simple fix to the namespace deletion

I haven't seen a simple way it could be done yet. It looks like a check for any resources with a soft finalizer would need to be added around here https://github.com/kcp-dev/kcp/blob/main/pkg/syncer/namespace/namespace_upstream_process.go#L78-L81

**Comment by david-martin** [comment]
https://github.com/kcp-dev/kcp-glbc/compare/main...david-martin:kcp-glbc:292-skupper-poc

Notes on how to run the demo locally are in https://github.com/david-martin/kcp-glbc/blob/292-skupper-poc/skupper_poc.md along with some open questions & discussion points.

![image](https://user-images.githubusercontent.com/878251/201952396-9a1e6e8f-49be-40f8-874d-eab9ae8cdf48.png)
