### ISSUE TITLE
Workload Readiness Checks

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#300]
**What**

With an application deployed to k8s, you have the option of providing a readiness probe which will decide whether an application will receive traffic through a k8s service https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes

Currently, we do no check to see if the application an ingress is targeting is ready to accept requests before setting up the DNSRecord. We update the DNS as soon as we see the ingress has a load balancer assigned its status. This does not mean that the application is necessarily ready to accept traffic. 
This kind of check is also important when we consider applications moving across cluster clusters. Before we update the DNS to move traffic to the new instance of the workload, we want to ensure that the workload(s) being targeted by the ingress are ready. 

We have support for adding a health check via annotations to an ingress. This may be enough for externally accessible applications. Do we want to also offer some functionality that will support applications running on an internal network and not exposed externally.

- [ ] Explore using available replicas to decide when the DNS for a workload should be updated (we should look into deployment, deploymentconfig and demonsets to check they have the same kind of status).  
- [ ] Explore a "health check" like API that allows something like a label selector and a timeout, it should also support a http endpoint (IE what we have in an annotation currently).
- [ ] create Steel thread/Poc and Design doc

**Comment by philbrookes** [comment]
## Workload Readiness
### Problem Statement
At present we create a DNS Record and ultimately a published DNS zone for each ingress. The targets in that record are discovered by searching the status of each service targeted by any rules in the ingress and adding all loadbalancers discovered there, these DNS Record targets are published to a DNS Zone regardless of their state. This can lead to a published zone targeting a sync target with an unhealthy or not ready workload.

### Diagrams
[Diagrams](https://lucid.app/lucidchart/b8689953-4062-4357-b387-1a522b6fc834/edit?invitationId=inv_08da6a04-79f1-4025-a516-4e70d9effa1b#)

### Disambiguation
- DNS Record: The resource created by GLBC in KCP
- DNS Zone: The record presented to the DNS provider to publicly published

### Proposal
To correct this, we will be adding a mechanism to allow our controller to interrogate - based on configuration - the workload on each sync target and in the DNS Record mark any targets that are unhealthy as not fit for publishing to the DNS Zone.

As this mechanism is strongly connected to the DNS endpoint health check we already make use of, this will be incorporated into this proposal.

This is implemented with the following steps:

#### Add a Health Check Policy CRD
The HealthCheckPolicy will have a few spec areas:

##### Target
This will specify a manner to determine which ingress type objects that this HealthCheck is applied to (e.g. all in a namespace, or in any namespace but with a label, or all in a workspace).

##### Policies > DNS
This will contain an array, each element will be like the existing DNS Health check data which is passed to the DNS provider so that it can create DNS Health Checks.

##### Policies > Deployments
This contains an array, each element will be a simple configuration specifying an optional labelselector to identify which deployment to apply this policy to (e.g. `criticalDeployment: true`), and a required field describing what the expected minimum available replicas should be.

#### Reconcile the DNS Record targets from the Ingress Controller
As before, all targets regardless of health will be added to the DNS Record.

#### Reconcile the Health Check Policy
See linked flow diagram of reconciler logic.

When a health check policy is reconciling it will execute the health check against all deployments related to it’s targeted ingresses, applying the health check policy to mark the target as healthy or not in the DNS Record.

It will also ensure the DNS Health checks are properly reconciled to the DNS provider.

**N.B.** A key part of this delivery is that the update of any deployment will also trigger a reconcile of any health checks which target ingresses that use that deployment - so that deployments going healthy / unhealthy are detected immediately.

#### Reconcile the DNS Record targets to the DNS Zone
The DNS Reconciler will be updated to only consider healthy targets as ready to send to the DNS zone, and use this as the comparison to ascertain if the zone requires updating or not.

#### Impact on workload migration
Currently workload migration assumes a workload is ready for traffic as soon as a loadbalancer is present on the service. This logic will need to be updated to check for health check policies and use those - if present - to determine health.

Also, currently the grace period for migration starts as soon as the workload is asked to move, this grace period should not start until the “gaining” sync target is reporting a healthy workload.

**Comment by maleck13** [comment]
@philbrookes why are we only allowing deployments to be targeted?

**Comment by philbrookes** [comment]
@maleck13 I did consider making it more open to extending like you have suggested, and I am happy to update to that, if you still think that is a good way to go. When we discussed it before you suggested that it would be wise to go for a very simple first implementation, and allow requirements to drive the more complex configurations once they are discovered, have you changed your opinion on that?

**Comment by maleck13** [comment]
If we allow a separate API for defining a health check and focus that initially only on the externally accessible applications but allow that check to be applied to multiple ingresses (IE they all have a /health endpoint ) that may be enough at this point? 
When setting up the DNS if there is a health check specified, it is also set up. This health check then should fail until the application is ready to accept traffic. Once the health check has passed then the IP will be returned as part of the DNS response

**Comment by maleck13** [comment]
https://github.com/kcp-dev/kcp-glbc/issues/81 duplicate
