### ISSUE TITLE
Continuous deployment via argo

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#353]
## Issue Description

The deploy script while use does a lot of work and generates resources on the fly. To bring us closer to being able to use a gitops approach, we want to have any resources needed in the repo with sane dev defaults but then use kustomize to allow to override for different environments

- [x] #368
- [x] #355
- [x] #369
- [x] #367
- [x] #373

**Comment by maleck13** [comment]
@mikenairn could you take a look

**Comment by david-martin** [comment]
1 option to get resources into the repo with sane dev defaults would be to check-in the output of the local-setup script (or at least the output from the kustomize commands in it). We'd need a CI job that verifies the checked in files are the latest generated, but we have examples of that already.

For overwriting & different environments, kustomize can be used as required from the source files.

For the identityHash, can a static dev value be used?

**Comment by mikenairn** [comment]
It was always the intention to have the kustomize config have defaults that would work out of the box to deploy glbc, with my hope that we would eventually be able to do it all via a command like `kubectl apply -k https://github.com/Kuadrant/kcp-glbc/tree/main/config/default`. The closer we can get to being able to do this will make any Git Ops setup we might want to do a lot easier since we can just override everything as required per env.

Most things are already in the kustomize dir with the exception of an issuer, currently being worked on, and the APIBindings and APIExports which are a bit trickier since we currently need to query the running cluster to get the identityHash. These two things i believe are the only k8s resources that glbc currently depends on that are not already created as part of the GLBC kustomize config.

The deploy script itself isn't actually doing much in terms of deploying GLBC, it does eventually just call our kustomization to install our controller. Most of what it is doing currently is around creating workspaces and synctargets, setup inside of KCP, that needs to be in place before we can install GLBC. Some of which is only needed because we actually run the controller in KCP. This however is slowly becoming less complicated, especially now we are moving to a single workspace containing everything.

**Comment by maleck13** [comment]
@david-martin modified the name of this, feel free to change the description and task around as you see fit

**Comment by maleck13** [comment]
@david-martin @roivaz wondering if we anticipate more work in actually getting to point Argo is doing the work for us?

**Comment by david-martin** [comment]
@maleck13 Yes, for sure.
The majority is tracked downstream in jira (https://issues.redhat.com/browse/HCG-148) as it's not really open source friendly.
